FROM node:20 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
ARG API_BASE=http://localhost:8080/api/v1
ENV VITE_API_BASE=$API_BASE
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
